# This job is used by buildImage() as an owner of the various resources it
# spawns so that for GC it simply needs to delete the job. The actual container
# here isn't used for anything (other than staying alive for 24h).

kind: Template
apiVersion: v1
metadata:
  name: clean-up
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: "${NAME}"
  spec:
    ttlSecondsAfterFinished: 100
    template:
      spec:
        containers:
        - name: "${NAME}"
          image: registry.fedoraproject.org/fedora:34
          command:
          - sleep
          - 24h
        restartPolicy: Never
parameters:
- name: NAME
  required: true
  value: cleanupJob
