# This job is used by buildImage() as an owner of the various resources it
# spawns so that for GC it simply needs to delete the job. The actual container
# here isn't used for anything (other than staying alive for 24h).

kind: Template
apiVersion: template.openshift.io/v1
metadata:
  # the name doesn't matter since we don't actually create a template object
  # from this; we just instantiate from it client-side
  name: unused
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: "${NAME}"
  spec:
    ttlSecondsAfterFinished: 100
    template:
      spec:
        containers:
        - name: "${NAME}"
          image: registry.fedoraproject.org/fedora-minimal:latest
          command:
          - sleep
          - 24h
        restartPolicy: Never
parameters:
- name: NAME
  required: true
